COMP: Error in definition of annonymous enumeration.
BRAINSCommonLib/Slicer3LandmarkIO.h:78:1:
error: ‘void WriteITKtoSlicer3Lmk(const string&, const LandmarksMapType&, SLICER_LANDMARK_FILE_TYPE)’,
declared using anonymous type, is used but never defined [-fpermissive]